version: '3'

services:
  php:
    container_name: php
    build: ./dockerfiles/php
    volumes: 
      - ./src:/var/www

  nginx:
    container_name: nginx
    build: ./dockerfiles/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/logs/nginx
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dockerfiles/nginx/server.crt:/etc/nginx/server.crt
      - ./dockerfiles/nginx/server.key:/etc/nginx/server.key
    depends_on:
      - php

  mysql:
    container_name: mysql
    build: ./dockerfiles/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: develop
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./logs/mysql:/var/logs/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - php
